FROM debian:bullseye

RUN apt update && apt-get update -y && \
	apt install apt-transport-https lsb-release ca-certificates wget -y && \
	apt-get install software-properties-common -y && \
	add-apt-repository ppa:certbot/certbot -y

RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg && \
	sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'

RUN apt install php7.4 php7.4-fpm php7.4-curl php7.4-mbstring php7.4-mysql php7.4-fpm -y

RUN apt-get install unzip -y && \
	wget https://wordpress.org/latest.zip

RUN mkdir -p /var/www/html/ && \
	unzip latest.zip -d /var/www/html/

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

RUN apt-get install sudo -y

RUN apt-get install mariadb-client -y

RUN chown -R www-data:www-data /var/www/html/ && \
	chmod -R 755 /var/www/html/ && \
	chown -R www-data:www-data /var/www/html/wordpress  && \
	chmod -R 755 /var/www/html/wordpress && \
	sed -i "s/listen =.*/listen = 9000/" /etc/php/7.4/fpm/pool.d/www.conf

RUN mkdir -p /run/php && \
	chown www-data:www-data /run/php 

COPY ./tools/setup_wordpress.sh ./



CMD [ "bash", "setup_wordpress.sh"]
