FROM debian:bullseye

RUN apt-get update && \ 
	apt-get -y install nginx && \
	mkdir /etc/nginx/ssl && apt-get -y install openssl && \
	openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/dongkseo.42.fr.key -out /etc/nginx/ssl/dongkseo.42.fr.crt -subj "/C=KU/ST=seoul/L=seoul/O=School42/OU=42/CN=localhost"

RUN mkdir -p /var/www/wordpress

COPY ./tools/conf/default ./etc/nginx/sites-available/

COPY ./tools/setup_nginx.sh ./

CMD [ "bash", "setup_nginx.sh"]
