FROM debian:bullseye

RUN apt-get update && apt-get -y install nginx
RUN mkdir /etc/nginx/ssl && apt-get -y install openssl
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/dongkseo.42.fr.key -out /etc/nginx/ssl/dongkseo.42.fr.crt -subj "/C=KU/ST=seoul/L=seoul/O=School42/OU=42/CN=localhost"

RUN apt install wget -y

RUN apt update
RUN apt-get install software-properties-common -y
RUN add-apt-repository ppa:certbot/certbot -y
RUN apt-get install certbot python3-certbot-nginx -y

RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg

RUN sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'


RUN apt install php7.4 php7.4-fpm php7.4-curl php7.4-mbstring php7.4-mysql php7.4-fpm -y

RUN apt-get install unzip -y

RUN chmod -R 777 /var/www/html

RUN apt-get -y install mariadb-server

RUN apt-get -y install mariadb-client

RUN wget https://wordpress.org/latest.zip

RUN unzip latest.zip -d /var/www/html/


RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

RUN apt-get install sudo -y


RUN chown -R www-data:www-data /var/www/html/wordpress
RUN chmod -R 755 /var/www/html/wordpress

RUN cd /var/www/html/wordpress && \
	sudo -u www-data wp config create --dbname=WordPress --dbuser=dongkseo --dbpass=6071 --dbhost=localhost --path=/var/www/html/wordpress --skip-check
RUN rm /var/www/html/wordpress/wp-config-sample.php


COPY .env /var/www/html/wordpress/

COPY ./default ./etc/nginx/sites-available/

COPY ./docker_build.sh ./

COPY ./index.php /var/www/html/

COPY ./my.cnf /etc/mysql/

COPY ./50-server.cnf /etc/mysql/mariadb.conf.d/

COPY ./init.sql ./

RUN chmod +x docker_build.sh

CMD ["/bin/bash", "./docker_build.sh"]
